import axios from "@/axios";

export default {
  // eslint-disable-next-line no-unused-vars
  enrollInmate ({ commit }, payload) {
    return new Promise((resolve, reject) => {
      let formData = new FormData()
      formData.append('inmate_ref_no', payload.enrollmentForm.refNo)
      formData.append('inmate_last_name', payload.enrollmentForm.lastname)
      formData.append('inmate_first_name', payload.enrollmentForm.firstname)
      formData.append('inmate_other_name', payload.enrollmentForm.othernames)
      formData.append('inmate_gender', payload.enrollmentForm.genderSelected)
      formData.append('inmate_dob', payload.enrollmentForm.dob)
      formData.append('inmate_local_state', payload.enrollmentForm.stateSelected)
      // formData.append('inmate_foreign_state', payload.enrollmentForm.stateSelected)
      formData.append('inmate_lga', payload.enrollmentForm.lgaSelected)
      formData.append('inmate_home_town', payload.enrollmentForm.hometown)
      formData.append('inmate_address', payload.enrollmentForm.address)
      formData.append('inmate_city', payload.enrollmentForm.city)
      formData.append('inmate_nationality', payload.enrollmentForm.nationalitySelected)
      formData.append('inmate_religion', payload.enrollmentForm.religionSelected)
      formData.append('inmate_next_of_kin', payload.enrollmentForm.nokInfo)
      formData.append('inmate_marital_status', payload.enrollmentForm.maritalSelected)
      formData.append('inmate_spouse_information', payload.enrollmentForm.spouseInfo)
      formData.append('inmate_children', payload.enrollmentForm.children)
      formData.append('inmate_category', payload.enrollmentForm.categorySelected)
      formData.append('inmate_charges', payload.enrollmentForm.chargesInfo)
      formData.append('inmate_court_state', payload.enrollmentForm.courtStateSelected)
      formData.append('inmate_court_type', payload.enrollmentForm.courtSelected)
      formData.append('inmate_judge', payload.enrollmentForm.judge)
      formData.append('inmate_judgement', payload.enrollmentForm.judgementFile.name)
      formData.append('inmate_sentence_date', payload.enrollmentForm.sentenceDate)
      formData.append('inmate_sentence_start_date', payload.enrollmentForm.sentenceStartDate)
      formData.append('inmate_sentence_duration', payload.enrollmentForm.sentenceDuration)
      formData.append('inmate_sentence_end_date', payload.enrollmentForm.sentenceEndDate)
      formData.append('inmate_others', payload.enrollmentForm.otherInfo)
      formData.append('inmate_blood_group', payload.enrollmentForm.bloodGroupSelected)
      formData.append('inmate_genotype', payload.enrollmentForm.genotypeSelected)
      formData.append('inmate_ailment', payload.enrollmentForm.ailments)
      formData.append('inmate_disabilities', payload.enrollmentForm.disabilities)
      formData.append('inmate_height', payload.enrollmentForm.height)
      formData.append('inmate_weight', payload.enrollmentForm.weight)
      formData.append('inmate_weight', payload.enrollmentForm.weight)
      formData.append('inmate_cs_id', '1')
      formData.append('inmate_country_residence', payload.enrollmentForm.countrySelected)
      axios({url: 'inmate/new_inmate', data: formData, method: 'POST'})
        .then(response => {
          resolve(response)
        })
        .catch(error => {
          reject(error)
        })
    })
  }
}
